---
- name: install mariadb server
  apt:
          name=mariadb-server
          update_cache=yes
          state=latest
- name: supression server conf
  file:
          path: /etc/mysql/mariadb.conf.d/50-server.cnf
          state: absent
- name: envoyer server conf
  template:
          src: ../templates/50servercnf.j2
          dest: /etc/mysql/mariadb.conf.d/50-server.cnf
- name: copier mon script
  copy:
          src: pymysqlinstall.sh
          dest: /
          owner: root
          group: root
          mode: '0755'
- name: installer pymysql 
  command: sh /pymysqlinstall.sh
- name: set root passwd
  mysql_user:  
          name: root
          password: "{{ mysql_root_mdp }}"
          login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: restart mysql      
- name: remove all anonym user accounts          
  mysql_user:
          name: ''
          host_all: yes
          state: absent
          login_user: root
          login_password: "{{ mysql_root_mdp }}"
  notify: restart mysql
- name: remove test data base
  mysql_db:
          name: test
          state: absent
          login_user: root
          login_password: "{{ mysql_root_mdp }}"
  notify: restart mysql        
- name: creer user db
  community.mysql.mysql_user:
          name: "{{ mysql_user_login }}"
          password: "{{ mysql_user_mdp }}" 
          priv: '*.*:ALL,GRANT'
          host: 0.0.0.0      
          state: present
          login_user: root
          login_password: "{{ mysql_root_mdp }}"
          login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: restart mysql
